apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8sinsight.fullname" . }}-secret
  labels:
    {{- include "k8sinsight.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwtSecret: {{ .Values.auth.jwtSecret | quote }}
  defaultAdminPassword: {{ .Values.auth.defaultAdminPassword | quote }}
  dbUsername: {{ .Values.postgresql.auth.username | quote }}
  dbPassword: {{ .Values.postgresql.auth.password | quote }}
  dbName: {{ .Values.postgresql.auth.database | quote }}
